### ISSUE TITLE
ENUM characters ¼ ½ ¾

### ISSUE THREAD

**Issue by RichAyotte** [mickhansen/graphql-sequelize#151]
An empty value is returned when splitting on ¼ ½ ¾ and an error is thrown on https://github.com/mickhansen/graphql-sequelize/blob/master/src/typeMapper.js#L95

``` javascript
const specialChars = /[^a-z\d_]/i;
const value = '¾'

sanitizedValue = value
.split(specialChars)
.reduce((reduced, val, idx) => {
    let newVal = val;
    if (idx > 0) {
        console.log(idx, val)
        newVal = `${val[0].toUpperCase()}${val.slice(1)}`;
    }
    return `${reduced}${newVal}`;
})
```

https://jsfiddle.net/RichAyotte/x25qm45r/

**Comment by mickhansen** [comment]
That's a specific case

**Comment by Alexsey** [comment]
This merge request https://github.com/mickhansen/graphql-sequelize/pull/502 should fix it

**Comment by RichAyotte** [comment]
#502 didn't solve this issue and I'm not sure what the right approach is but here's what I propose. Since GraphQL requires the key to be a string that matches `/^[_a-zA-Z][_a-zA-Z0-9]*$/ ` We could transform the [¼](http://www.fileformat.info/info/unicode/char/00bc/index.htm) [½](http://www.fileformat.info/info/unicode/char/00BD/index.htm) [¾](http://www.fileformat.info/info/unicode/char/BE/index.htm) characters to their HTML entity names.
```
¼ - > 'frac14'
½ -> 'frac12`
¾ -> 'frac34'
```
If this is acceptable, would you prefer a PR for just these characters or should others be included?

**Comment by mickhansen** [comment]
@RichAyotte I'm quite amazed people have enums with those values. But yes some sort of map is probably the best way to go, as long as it's consistent and tested

**Comment by RichAyotte** [comment]
Fixed in https://github.com/mickhansen/graphql-sequelize/pull/531
