### ISSUE TITLE
defaultListArgs does not support query variables (eg. variable value for `where` becomes null)

### ISSUE THREAD

**Issue by pre** [mickhansen/graphql-sequelize#468]
Query variables with array values do not seem to work. The same query works when the array values are passed directly in the query. However, if the array values are passed using query variables, the resolver just sees `null`. 

The following query loses the variable value of `$nicks` which becomes `null` in the resolver:

```graphql
query Users($nicks:[String!]) {
  users(where: {nick: {
    	in: $nicks} }) {
    id
    lastname 
    firstname    
  }
}

variables:
{"nicks": ["Carrie", "Tim"]}
```

The query works, when I pass the values directly in the query without using variables: 
```graphql
query Users($nicks:[String!]) {
  users(where: {nick: {
    	in: ['This', 'Works']} }) {
    id
    lastname 
    firstname    
  }
}
```

The route looks like this:
```javascript
users: {
  type: new GraphQLList(userType),
  args: defaultListArgs(),
  resolve: resolver(models.User, {
    before: (opts, args) => {
      console.log("!!!!!!!!!! before opts where", opts.where.nick);
      console.log("!!!!!!!!!! before args", args);
      return options;
    }
  })
}
```

And the debugging output looks like:
```
!!!!!!!!!! before opts { where: { nick: { '$in': null } }, 
  attributes: [ ...attrs here... ], logging: undefined }
!!!!!!!!!! before args { where: { nick: { in: null } } }
```

It doesn't matter whether I pass the array as `in: [$nicks]` or `in: $nicks`, the resulting value is always null (either `null` or `[Object]` where `Object` is `null` when looked into). 

I have spent quite some time trying to figure out this, so any tips about the direction where to debug further or fix this, would be welcome.

**Comment by pre** [comment]
Possibly related issue: https://github.com/mickhansen/graphql-sequelize/issues/250

**Comment by mickhansen** [comment]
graphql-sequelize doesn't modify args, do you have the same issue with pure graphql?

**Comment by pre** [comment]
You are right. I also get null without using graphql-sequelize:

```javascript
        resolve: (root, args) => {
          console.log("!!!!!!!!!! root", root);
          console.log("!!!!!!!!!! args", args);
        }
```

outputs 
```
!!!!!!!!!! root undefined
!!!!!!!!!! args { where: { flowdockNick: { in: null } } }
```

I am using graphql-server-express, would you suggest this is a bug in that project?

**Comment by pre** [comment]
Actually, now that I looked into it with fresh eyes, I have a hunch that the problem is in the way how `defaultListArgs` [handles the array json value](https://github.com/mickhansen/graphql-sequelize/blob/a4b92d617524d77841fb52eda9f25c649951b433/src/types/jsonType.js). 

I reopened the issue until I have time to look deeper into it. This is now my primary suspect.

**Comment by mickhansen** [comment]
@pre Hmm, yes that might be very likely, i haven't used defaultListArgs in a while myself (primarily use relay-spec graphql)

**Comment by pre** [comment]
jsonType.js doesn't seem to handle Variable at all. 

When I add the following debugs:
```javascript
  [_language.Kind.LIST]: function (ast) {
    return ast.values.map(astItem => {
      console.log("########### astItem", astItem);
      console.log("########### astItem parsed", JSONType.parseLiteral(astItem));
      return JSONType.parseLiteral(astItem);
    });
  },
  [... clip ... ] 
};

const JSONType = new _graphql.GraphQLScalarType({
  name: 'SequelizeJSON',
  description: 'The `JSON` scalar type represents raw JSON as values.',
  serialize: value => value,
  parseValue: value => value,
  parseLiteral: ast => {
    const parser = astToJson[ast.kind];
    console.log("----------- parser", parser);
    console.log("----------- astToJson", astToJson[ast.kind]);
    return parser ? parser.call(undefined, ast) : null;
  }
});
```

Then I see the following output:

A) without using variables, ie passing value HELLO in the query:

```
########### astItem { kind: 'StringValue',
  value: 'HELLO',
  loc: { start: 96, end: 101 } }
----------- parser function (ast) {
    return _graphql.GraphQLString.parseLiteral(ast);
  }
----------- astToJson function (ast) {
    return _graphql.GraphQLString.parseLiteral(ast);
  }
########### astItem parsed HELLO
----------- parser function (ast) {
    return _graphql.GraphQLString.parseLiteral(ast);
  }
----------- astToJson function (ast) {
    return _graphql.GraphQLString.parseLiteral(ast);
  }
```


B) using variable $nicks to pass HELLO:

```
########### astItem { kind: 'Variable',
  name:
   { kind: 'Name',
     value: 'nicks',
     loc: { start: 97, end: 110 } },
  loc: { start: 96, end: 110 } }
----------- parser undefined
----------- astToJson undefined
########### astItem parsed null
----------- parser undefined
----------- astToJson undefined
```

***

I added the following to jsonType.js: 
```javascript
  [_language.Kind.VARIABLE]: function (ast) {
    console.log("/////// VARIABLE ast", ast);
    return new _graphql.GraphQLList(ast);
  },
```

and I get the following output:
```
/////// VARIABLE ast { kind: 'Variable',
  name:
   { kind: 'Name',
     value: 'nicks',
     loc: { start: 97, end: 110 } },
  loc: { start: 96, end: 110 } }
Error: Can only create List of a GraphQLType but got: [object Object].
```

Do you have an idea where could I get the actual variable value which I could then pass to `GraphQLList` ? The `ast` variable does only seem to contain the variable definition, not the variable value.

**Comment by tbarho** [comment]
@pre From what I understand (and I'm fairly new to graph), making JSONType a `GraphQLScalarType` prevents it from being able to pick up any variables, since the field isnt being resolved with `info.variableValues`.

Not a big deal, unless you *don't* want to use Relay *and* you would like to be able to do a query like:

```
  query ($search: String) {
    customers(
      where: {
        or: [
          { email: { like: $search } },
          { name: { like: $search } }
        ]
      },
    ) {
      id,
      name,
      email
    }
  }
```

I'm not 100% sure, but I think using GraphQLScalarType, I think, makes this type of query impossible with `graphql-sequelize`.  @mickhansen can you confirm?

Also, @pre curious if you found any workarounds...

**Comment by Alexsey** [comment]
Pull request for this https://github.com/mickhansen/graphql-sequelize/pull/506

**Comment by Yehonal** [comment]
I still have this issue, can anyone confirm?

```
query accGet($account: Int!){
  accountGet(where: {id: $account}){
        username
  }
}
```

this causes null value in where

**Comment by Yehonal** [comment]
Workaround: use a json string instead

![image](https://user-images.githubusercontent.com/147092/53565996-4cea5880-3b5b-11e9-9306-f9b9907ba22d.png)

It works
